create login [asa.sql.workload01] with password = '#PASSWORD#'
create login [asa.sql.workload02] with password = '#PASSWORD#'
create login [asa.sql.import01] with password = '#PASSWORD#'
create login [asa.sql.import02] with password = '#PASSWORD#'
create login [asa.sql.highperf] with password = '#PASSWORD#'