Remove-Module solliance-synapse-automation
Import-Module ".\artifacts\environment-setup\solliance-synapse-automation"

Install-Module -Name Az -AllowClobber -Scope CurrentUser
Install-Module -Name Az.CosmosDB -AllowClobber -Scope CurrentUser

Import-Module Az.CosmosDB

Connect-AzAccount

$subscriptionId = "cccbcfbd-0a1f-45ee-b948-2393697c32b0"
$resourceGroupName = "Synapse-L400-Workshop-175799"
$templatesPath = ".\artifacts\environment-setup\templates"
$workspaceName = "asaworkspace03"
$cosmosDbAccountName = "asacosmosdb03"
$cosmosDbDatabase = "CustomerProfile"
$cosmosDbContainer = "OnlineUserProfile01"
$dataLakeAccountName = "asadatalake03"
$keyVaultName = "asakeyvault03"

$synapseToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiJodHRwczovL2Rldi5henVyZXN5bmFwc2UubmV0IiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvY2VmY2I4ZTctZWUzMC00OWI4LWIxOTAtMTMzZjFkYWFmZDg1LyIsImlhdCI6MTU4ODA1Mjg4MSwibmJmIjoxNTg4MDUyODgxLCJleHAiOjE1ODgwNTY3ODEsImFjciI6IjEiLCJhaW8iOiJBU1FBMi84UEFBQUFaNFFFbnhOSnROU1U0WE05aGJJdnJmN05JRTkxcjhhNkVNdXVsdm0yMi9VPSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJlYzUyZDEzZC0yZTg1LTQxMGUtYTg5YS04Yzc5ZmI2YTMyYWMiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IjE3NTc5OSIsImdpdmVuX25hbWUiOiJPRExfVXNlciIsImlwYWRkciI6Ijc5LjExOC4xLjIyMyIsIm5hbWUiOiJPRExfVXNlciAxNzU3OTkiLCJvaWQiOiIzNzJiN2Q1MS0xNmE0LTQ0NjctOTZlOS1jMTY5ZGUwNTQxYTMiLCJwdWlkIjoiMTAwMzIwMDBCNzQ5Qzk4QSIsInNjcCI6IndvcmtzcGFjZWFydGlmYWN0cy5tYW5hZ2VtZW50Iiwic3ViIjoiQnQ5XzFIc2QxWk5fMk1BVnJZUkd1SnZpRHhDc2JyM3V3UG9jRjRWbFFfYyIsInRpZCI6ImNlZmNiOGU3LWVlMzAtNDliOC1iMTkwLTEzM2YxZGFhZmQ4NSIsInVuaXF1ZV9uYW1lIjoib2RsX3VzZXJfMTc1Nzk5QG1zYXp1cmVsYWJzLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6Im9kbF91c2VyXzE3NTc5OUBtc2F6dXJlbGFicy5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJlYmhVSnFqUW9rS1YxSnp3SXRZY0FBIiwidmVyIjoiMS4wIn0.h7uacl9Azve3SloHclk8h5vyGzphfV-z4A3fCTx9vkrbVMjEz7Umy8d2MxTgrHnUnR1MimIZUQhnPbfgoQUBJZ1-BCPwXTfuPr0HthriGCBKdriEHarzzlJ4xUs-otqSk4KfltkNyoLS1uqIWguFep4P0aSdsHALLmRzyZFJbdeKnlOecHduvVpIx_QLS7lJTNKuwi7zpyiHGHblzxcAOlmv4rLjGytjdMrzji8NRmQiCoF-zIpYpv-8WFwhhPcXN6XVPdUjrICfotQ_fN2X-icKaNHpv3CPOrR1s53RTJsugTbKs-FmVgcBEBRTragnuqNpwKVzQkcQA5mq9l0yMw"
$managementToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2NlZmNiOGU3LWVlMzAtNDliOC1iMTkwLTEzM2YxZGFhZmQ4NS8iLCJpYXQiOjE1ODgwNTEwNzEsIm5iZiI6MTU4ODA1MTA3MSwiZXhwIjoxNTg4MDU0OTcxLCJhY3IiOiIxIiwiYWlvIjoiNDJkZ1lPaWFWZTVqRldGenR5ZktZcW5UdGdBbnhlQi9HeHhmYkQ2eG9IM0NCSnRUZkJzQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJlYzUyZDEzZC0yZTg1LTQxMGUtYTg5YS04Yzc5ZmI2YTMyYWMiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IjE3NTc5OSIsImdpdmVuX25hbWUiOiJPRExfVXNlciIsImlwYWRkciI6Ijc5LjExOC4xLjIyMyIsIm5hbWUiOiJPRExfVXNlciAxNzU3OTkiLCJvaWQiOiIzNzJiN2Q1MS0xNmE0LTQ0NjctOTZlOS1jMTY5ZGUwNTQxYTMiLCJwdWlkIjoiMTAwMzIwMDBCNzQ5Qzk4QSIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ilp4bkh0cnZ1OUVtWVNYX0dXcndSdThTUTBJUmlrZHA5UlI1aFdfaVF4NFUiLCJ0aWQiOiJjZWZjYjhlNy1lZTMwLTQ5YjgtYjE5MC0xMzNmMWRhYWZkODUiLCJ1bmlxdWVfbmFtZSI6Im9kbF91c2VyXzE3NTc5OUBtc2F6dXJlbGFicy5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJvZGxfdXNlcl8xNzU3OTlAbXNhenVyZWxhYnMub25taWNyb3NvZnQuY29tIiwidXRpIjoiOVJveExEX2JrMEc1NzlFUmR2b2VBQSIsInZlciI6IjEuMCJ9.o7OLZOtdCjK_UjNJrltJTKQPuTsb3wo3QV6BVplVPmUmCIOIs-Cj2VwL2FHAAspeH6gHS2Kt-Xei4cI5832ArlQxDNmOJE2S_5WbHG64QotmDnYdHFdH9KDEx735COL009E-HRPPQUb9J71QymAiXwwpoccJFLBWq8LaMMY-g97snV0Ifb4gcRDRg4BeEjzPPAInlcqAd7IPRhxEyjpZtUNYwG6i3ubYgvaleHJAl7h13bKOOqektQ0sMdipbolFDqXL5c2ca2xR3PvcCXozrS-Ur-2iOQTg3qMYbhlLkF4Vy3maMzvu_GrzeL5F_6IxClMMkGM21kJ377FIYZielg"


Create-KeyVaultLinkedService -TemplatesPath $templatesPath -WorkspaceName $workspaceName -Name $keyVaultName -Token $synapseToken

Create-IntegrationRuntime -TemplatesPath $templatesPath -SubscriptionId $subscriptionId -ResourceGroupName $resourceGroupName -WorkspaceName $workspaceName -Name "AzureIntegrationRuntime01" -CoreCount 16 -TimeToLive 60 -Token $managementToken

$storageAccountKey = List-StorageAccountKeys -SubscriptionId $subscriptionId -ResourceGroupName $resourceGroupName -Name $dataLakeAccountName -Token $managementToken

# Increase RUs in CosmosDB container

$container = Get-AzCosmosDBSqlContainer `
        -ResourceGroupName $resourceGroupName `
        -AccountName $cosmosDbAccountName -DatabaseName $cosmosDbDatabase `
        -Name $cosmosDbContainer

Set-AzCosmosDBSqlContainer -ResourceGroupName $resourceGroupName `
        -AccountName $cosmosDbAccountName -DatabaseName $cosmosDbDatabase `
        -Name $cosmosDbContainer -Throughput 5000 `
        -PartitionKeyKind $container.Resource.PartitionKey.Kind `
        -PartitionKeyPath $container.Resource.PartitionKey.Paths

$cosmosDbAccountKey = List-CosmosDBKeys -SubscriptionId $subscriptionId -ResourceGroupName $resourceGroupName -Name $cosmosDbAccountName -Token $managementToken

$result = Create-CosmosDBLinkedService -TemplatesPath $templatesPath -WorkspaceName $workspaceName -Name $cosmosDbAccountName -Database $cosmosDbDatabase -Key $cosmosDbAccountKey -Token $synapseToken

$statusResult = Invoke-RestMethod `
    -Uri https://asaworkspace03.dev.azuresynapse.net/operationResults/$($result.operationId)?api-version=2019-06-01-preview `
    -Method GET `
    -Headers @{ Authorization="Bearer $synapseToken" }
$statusResult