$azureUsername="AzureUserNameValue"
$azurePassword="AzurePasswordValue"
$AzureSQLPassword="AzurePasswordValue"
$azureTenantID="AzureTenantIDValue"
$azureSubscriptionID="AzureSubscriptionIDValue"
$deploymentID="DeploymentIDValue"
$odlId="ODLIDValue"
$TokenGeneratorClientId="1950a258-227b-4e31-a9cf-717495945fc2"